### ISSUE TITLE
Clarify whether a class can contain other classes in a classmap

### ISSUE THREAD

**Issue by dividedmind** [getappmap/appmap#43]
The section on [classmap](https://github.com/getappmap/appmap/#classmap) says:

> A class may contain classes and functions, but not packages.

But also:

> Each "class" must be the child of a "package".

Which is it?

**Comment by kgilpin** [comment]
Classes may not contain classes.

**Comment by dividedmind** [comment]
I'm going to reopen this since it disagrees with both the example and what appmap-ruby generates. It seems like it's "package+ class+ function".

**Comment by kgilpin** [comment]
Maybe I’m misremembering

**Comment by kgilpin** [comment]
Right so `package+ class+ function`

What’s definitely not allowed is `package function`
